{% set version = "2.2.0" %}

package:
  name: eccodes
  version: {{ version }}

source:
  url: https://software.ecmwf.int/wiki/download/attachments/45757960/eccodes-{{ version }}-Source.tar.gz
  fn: eccodes-{{ version }}-Source.tar.gz
  sha256: 1a4112196497b8421480e2a0a1164071221e467853486577c4f07627a702f4c3

build:
  number: 1
  skip: true  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake
    - boost 1.63.*
    - jasper
    - libpng >=1.6.28,<1.7
    - libnetcdf 4.4.*
    - perl 5.22.2.1
  run:
    - jasper
    - libpng >=1.6.28,<1.7
    - libnetcdf 4.4.*

test:
  commands:
    - codes_info
    - ls $(codes_info -s)
    - ls $(codes_info -d)
    - conda inspect linkages -p $PREFIX eccodes  # [not win]
    - conda inspect objects -p $PREFIX eccodes  # [osx]

about:
  home: https://software.ecmwf.int/wiki/display/ECC/ecCodes+Home
  license: Apache 2.0
  license_family: Apache
  summary: ECMWF ecCodes Copyright 2005-2017 ECMWF.

extra:
  recipe-maintainers:
    - kmuehlbauer
    - pelson
    - ocefpaf
    - kynan
