{% set version = "2.8.2" %}

package:
  name: eccodes
  version: {{ version }}

source:
  url: https://software.ecmwf.int/wiki/download/attachments/45757960/eccodes-{{ version }}-Source.tar.gz
  sha256: 36e6e73d654027b31c323b0eddd15e4d1f011ad81e79e9c71146ba96293d712a

build:
  number: 1
  skip: true  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake
    - perl 5.22.2.1
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - boost
    - jasper
    - libpng
    - libnetcdf
    - hdf5
  run:
    - jasper
    - libpng
    - libnetcdf
    - hdf5

test:
  commands:
    - codes_info
    - ls $(codes_info -s)
    - ls $(codes_info -d)
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://software.ecmwf.int/wiki/display/ECC/ecCodes+Home
  license: Apache 2.0
  license_family: Apache
  summary: ECMWF ecCodes Copyright 2005-2018 ECMWF.

extra:
  recipe-maintainers:
    - kmuehlbauer
    - pelson
    - ocefpaf
    - kynan
