travis:
  secure:
    BINSTAR_TOKEN: aW1gQMPWuwGBXXJ7PrZXjEVu+rajsy7HpJN5hOwt0O1jDbefeAIKn1Svq1Wlz5Q+CyVTAIp5fOVSmHKa7O0tuAPHDVNoYvGpuXumLHfydZsOZrnj1HFwVX4Ceokk3oWy5YRjZjfBBxZCCJO5sfCzvygsqSsCgr6R6ZpM/ILs1BpPbLnr8XeKTEeCT5Cn84+kGedc4X86gKyjGv+ei522n8B6Iwr/QVkSEcu6zjBCasJHgmqVnRS/WxN9EV8U3E6kngDgwZgH4OsPdeZAvUM2arpPFYrmPNrBMqtnPENkQWMqGOOkGkC+rqnKTGVAFpI2bPvRi2DetOpf7Ih0xFe2RGT+dNnSf7olcX6fEIrOBNddZKSS52GCBGd4IsEu56/tRANj7Md4RxgNXTkchnpUgNOdh17NYVxp43Ju54sdy5YYAiITYElsH32dGy2e/ZW4sxwkFyJ+fMq0DYh0XvE7eC9JrmRokZEvqTPFVTF5+Vdvks02job5iQdO0AOQPeAQjFQhQemlFeG5PovuQOB9EE05OWGsU3fo+7CF5xvoNiFmfCEwRhxTiYZnPQaH3QK9ktajaFnL9kI+0uX65r9RWOlVwBIXFlqYXWeeqARGsV5nO0t/TP+U23dunOMErgqNn4U4cRZyj7x75gktejj7FoWuliwMyO+kqmJJG04seRI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
